### ISSUE TITLE
Missing `utils` module

### ISSUE THREAD

**Issue by minhkhoi1026** [VITA-Group/Graph-Mixture-of-Experts#1]
Hi, I am reproducing the result of your paper. When I run the `graphproppred/main_pyg.py` file, it generated a below error:
```
Traceback (most recent call last):
  File "main_pyg.py", line 14, in <module>
    from utils import RandomDropNode
ModuleNotFoundError: No module named 'utils'
```
As the error state, there are no `utils` module in your code or in dependent package. Could you add the `utils` module?

**Comment by minhkhoi1026** [comment]
@Ir1d @Syzygianinfern0 @htwang14 could you check it?

**Comment by htwang14** [comment]
The file is uploaded. Thanks

**Comment by minhkhoi1026** [comment]
Thank you for your help, @htwang14!
