### ISSUE TITLE
Code Problems

### ISSUE THREAD

**Issue by sutongxu** [VITA-Group/Graph-Mixture-of-Experts#4]
python main_pyg.py --dataset ogbg-molhiv -n 8 --n1 4 -k 4 -d 150 --device 0 --gnn gcn-spmoe --coef 1

Run the command as above, result:
 raise Exception(“Now using drop node, which doesn't support mixed training/eval yet!”)
Exception: Now using drop node, which doesn't support mixed training/eval yet!

The problem is at line 305:
         else:
                raise Exception("Now using drop node, which doesn't support mixed training/eval yet!")
                print('Training mixed...')
                train_mixed(model, device, train_loader, train_loader_2hop, optimizer, dataset.task_type)
                print('Evaluating mixed...')
                train_perf = eval_mixed(model, device, train_loader, train_loader_2hop, evaluator)
                valid_perf = eval_mixed(model, device, valid_loader, valid_loader_2hop, evaluator)
                test_perf = eval_mixed(model, device, test_loader, test_loader_2hop, evaluator)

**Comment by spidercatfly** [comment]
I encountered the same issue, have you solved it?
Is it because it only supports either all one-hop or all two-hop experts?

**Comment by mumukehao** [comment]
I encountered the same issue, have you solved it?
